spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://110.42.155.172:3306/youth_learn
    username: root
    password: LiuLong123123+
  mvc:
    static-path-pattern: /static/**
#    favicon:
#      enabled: false

mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ll.youthlearn.entity
server:
  port: 8082